Note: The agents in this simulation package are computational
constructs powered by generative agents architecture and LLM. We
clarify that these agents lack human-like agency, consciousness,
and independent decision-making.
---
CURRENT TIME IS: 10000
CURRENT ENV FILE IS: ../../environment/frontend_server/storage/n_25_4/environment/0.json
Latoya Williams movement start
perceive
retrieve
plan
new_day First day
---
---
daily req:  ['wake up and complete the morning routine at 6:00 am', 'have breakfast at 7:00 am', 'work on her photography projects from 8:00 am to 12:00 pm', 'have lunch at 12:00 pm', 'continue working on photography projects from 1:00 pm to 4:00 pm', 'take a break and engage in conversations about the local mayor election from 4:00 pm to 5:30 pm', 'have dinner at 5:30 pm', 'review and organize her photography work from 6:00 pm to 7:00 pm']
---
---
---
---
Request timed out: HTTPSConnectionPool(host='api.openai.com', port=443): Read timed out. (read timeout=600)
ChatGPT ERROR
Traceback (most recent call last):
  File "/home/sngwon/workspace/generative_agents/reverie/backend_server/reverie.py", line 628, in <module>
    rs.open_server()
  File "/home/sngwon/workspace/generative_agents/reverie/backend_server/reverie.py", line 441, in open_server
    rs.start_server(10000)
  File "/home/sngwon/workspace/generative_agents/reverie/backend_server/reverie.py", line 383, in start_server
    next_tile, pronunciatio, description = persona.move(
  File "/home/sngwon/workspace/generative_agents/reverie/backend_server/persona/persona.py", line 242, in move
    plan = self.plan(maze, personas, new_day, retrieved)
  File "/home/sngwon/workspace/generative_agents/reverie/backend_server/persona/persona.py", line 38, in wrapper
    output=func(*args)
  File "/home/sngwon/workspace/generative_agents/reverie/backend_server/persona/persona.py", line 160, in plan
    return plan(self, maze, personas, new_day, retrieved)
  File "/home/sngwon/workspace/generative_agents/reverie/backend_server/persona/cognitive_modules/plan.py", line 29, in wrapper
    output=func(*args)
  File "/home/sngwon/workspace/generative_agents/reverie/backend_server/persona/cognitive_modules/plan.py", line 997, in plan
    _long_term_planning(persona, new_day)
  File "/home/sngwon/workspace/generative_agents/reverie/backend_server/persona/cognitive_modules/plan.py", line 29, in wrapper
    output=func(*args)
  File "/home/sngwon/workspace/generative_agents/reverie/backend_server/persona/cognitive_modules/plan.py", line 520, in _long_term_planning
    persona.scratch.f_daily_schedule = generate_hourly_schedule(persona, 
  File "/home/sngwon/workspace/generative_agents/reverie/backend_server/persona/cognitive_modules/plan.py", line 29, in wrapper
    output=func(*args)
  File "/home/sngwon/workspace/generative_agents/reverie/backend_server/persona/cognitive_modules/plan.py", line 128, in generate_hourly_schedule
    n_m1_activity += [run_gpt_prompt_generate_hourly_schedule(
  File "/home/sngwon/workspace/generative_agents/reverie/backend_server/persona/prompt_template/run_gpt_prompt.py", line 261, in run_gpt_prompt_generate_hourly_schedule
    output = safe_generate_response(prompt, gpt_param, 5, fail_safe,
  File "/home/sngwon/workspace/generative_agents/reverie/backend_server/persona/prompt_template/gpt_structure.py", line 326, in safe_generate_response
    curr_gpt_response, _ = GPT_request_edit(prompt, gpt_parameter, prompt_template=prompt_template)
  File "/home/sngwon/workspace/generative_agents/reverie/backend_server/persona/prompt_template/gpt_structure.py", line 19, in wrapper
    output, prompt_template=func(prompt, gpt_parameter, prompt_template)
ValueError: too many values to unpack (expected 2)
